repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: flake8
        args: [--max-line-length=200,--exclude=src/cook/*,--ignore=F403,--ignore=W503]
-   repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
    -   id: black
