simulate_streaming_random_sleep:
  min: 0.005
  max: 0.2

llm:
  openai:
    # TODO: 要能支持单次对话指定使用什么模型版本
#    model: gpt-3.5-turbo
    model: gpt-4
    organization: org-fC5Q2f4MQIEaTOa3k8vTQu6G

lark:
  app_token: LLwmbSyMcakFVJsM5yacT5Gqnse
  table_id: tbl2ww1H5VCfQzxL
  view_id: vewlGkI2Jp