version: '3.5'

services:
  ai-study-api:
    container_name: ai-study-api
    image: ai-study-api:latest
    command:  gunicorn -w 4 -b 0.0.0.0:5800 "flaskr:create_app('prod_docker')"  --timeout 300 --log-level debug --access-logfile /var/log/app.log  --capture-output
  ai-study-web:
    container_name: ai-study-web
    image:  ai-study-web:latest
    command:  ["serve", "-s", "build", "-l", "5000"]
    depends_on:
      - ai-study-api
    # ports: 
    #  - "5000:5000"
  # chat-plugin-nginx:
  #   container_name: chat-plugin-nginx
  #   image: nginx:latest
  #   ports: 
  #     - "8080:8080"
  #   depends_on:
  #     - chat-plugin-ui
  #     - chat-plugin-background
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  # mysql-server:
  #   container_name: mysql-server
  #   image: mysql:latest
  #   environment:
  #     MYSQL_ROOT_PASSWORD: Pa88word
  #     MYSQL_DATABASE: ai_asistant
  #   volumes:
  #     - ${DOCKER_VOLUME_DIRECTORY:-.}/volumes/mysql:/var/lib/mysql
  #     - ./smart-home-plugins/db/init.sql:/docker-entrypoint-initdb.d/init.sql 
  # redis-server:
  #   container_name: redis-server
  #   image: redis:latest
  #   restart: always

