kind: Deployment
apiVersion: apps/v1
metadata:
  name: smart-plugin-chatui
  namespace: openai-test
  labels:
    app: smart-plugin-chatui
  annotations:
    deployment.kubernetes.io/revision: '1'
    kubesphere.io/creator: project-admin-test
    kubesphere.io/description: smart-plugin-chatui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-plugin-chatui
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: smart-plugin-chatui
      annotations:
        kubesphere.io/creator: project-admin-test
        kubesphere.io/imagepullsecrets: '{"container-npzrlm":"aliyun-registy-secret-kattgatt"}'
    spec:
      volumes:
        - name: host-time
          hostPath:
            path: /etc/localtime
            type: ''
      containers:
        - name: container-npzrlm
#          image: registry.cn-hangzhou.aliyuncs.com/kattgatt-app/smart-plugin-chatui:SNAPSHOT-6
          image: $REGISTRY/$ALIYUNHUB_NAMESPACE/smart-plugin-chatui:SNAPSHOT-$BUILD_NUMBER
          ports:
            - name: tcp-5000
              containerPort: 5000
              protocol: TCP
          resources: {}
          volumeMounts:
            - name: host-time
              readOnly: true
              mountPath: /etc/localtime
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      nodeSelector:
        kubernetes.io/hostname: worker4
      serviceAccountName: default
      serviceAccount: default
      securityContext: {}
      imagePullSecrets:
        - name: aliyun-registy-secret-kattgatt
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
