name: deploy-

on:
  push:
    branches: ["master"] # Trigger only on push to the develop branch
  pull_request:
    branches: [ "master" ]
     
 

jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH to remote server and execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            cd  /data/ai-shifu/deploy-config/
            git pull
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-api.sh
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-web.sh
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-admin-web.sh