name: deploy-to-prod-env

on:
  push:
    branches: ["master"] # Trigger only on push to the develop branch



jobs:
  build-and-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: SSH to remote server and execute deployment script
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            cd  /data/ai-shifu/deploy-config/
            git pull
      - name: Deploy API
        if: contains(github.event.head_commit.message, 'src/api/') || contains(github.event.commits[*].modified, 'src/api/')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-api.sh
      - name: Deploy Web
        if: contains(github.event.head_commit.message, 'src/web/') || contains(github.event.commits[*].modified, 'src/web/')
        uses: appleboy/ssh-action@master
        with:
           host: ${{ secrets.PROD_DEPLOY_HOST }}
           username: ${{ secrets.USERNAME }}
           key: ${{ secrets.PROD_SSH_KEY }}
           port: ${{ secrets.PORT }}
           script: |
             sudo su -
             bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-web.sh
      - name: Deploy Admin Web
        if: contains(github.event.head_commit.message, 'src/admin-web/') || contains(github.event.commits[*].modified, 'src/admin-web/')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-admin-web.sh
      - name: Deploy Cook
        if: contains(github.event.head_commit.message, 'src/cook/') || contains(github.event.commits[*].modified, 'src/cook/')
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_DEPLOY_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PROD_SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            sudo su -
            bash /data/ai-shifu/deploy-config/build-and-deploy-shifu-admin-web.sh
