name: pre-commit
on:
  [push, pull_request]
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # get full commit history to correctly detect changed files
      - uses: pre-commit/action@v3.8.0
        with:
          extra_args: --all-files
